const Queries = {
    // QUERY PARA TODO EL SOCIO ADMINISTRATIVO
    getAllSocioAdmin:
        `SELECT 
        Nombres,
        Apellidos,
        Cargo,
        Cliente_Area,
        Programa_Area,
        Servicio,
        Sede,
        Etiquetas_Especiales_1,
        Etiquetas_Especiales_2,
        Etiquetas_Especiales_3,
        Fecha_Ingreso_Compania,
        Fecha_Ingreso_Formacion,
        Fecha_Ultima_Migracion,
        Usuario_Red,
        Plataforma_1,
        Usuario_Plataforma_1,
        Plataforma_2,
        Usuario_Plataforma_2,
        Plataforma_3,
        Usuario_Plataforma_3,
        Plataforma_4,
        Usuario_Plataforma_4,
        Plataforma_5,
        Usuario_Plataforma_5,
        Fecha_Nacimiento,
        Pais_Nacimiento,
        Departamento_Nacimiento,
        Ciudad_Nacimiento,
        Edad,
        Genero,
        Tipo_Documento,
        Estado_Civil,
        Etnia,
        Grupo_Sanguineo,
        Factor_Sanguineo,
        Centro_Costos,
        Tipo_De_Centro_Costos,
        Estado_Empleado,
        Tipo_de_Baja,
        Fecha_Aplicacion_Retiro,
        Fecha_Actualizacion_Retiro,
        Comentario_Retiro,
        Causal_Terminacion,
        Director_Area,
        Gerente_Responsable,
        Jefe,
        Coordinador,
        Jefe_Inmediato,
        Correo_Corporativo,
        Correo_Personal,
        Departamento_Residencia,
        Ciudad_Residencia,
        Zona_Residencia,
        Barrio_Residencia,
        Direccion_Residencia,
        Cubrimiento_Ruta,
        Telefono_Fijo_Principal,
        Telefono_Fijo_Secundario,
        Telefono_Celular_Principal,
        Telefono_Celular_Secundario,
        Contacto_Emergencia,
        Telefono_Contacto_Emergencia,
        Vehiculo_Propio,
        Tipo_Vehiculo,
        Computador_En_Casa,
        Internet_En_Casa,
        Velocidad_Internet,
        Sistema_Operativo_Computador,
        Memoria_RAM,
        Numero_Hijos,
        Numero_Personas_A_Cargo,
        Fondo_Pensiones,
        Fondo_Cesantias,
        Entidad_Salud,
        ARL,
        Caja_Compensacion_Familiar,
        Dias_Vacaciones,
        Estudio_Pregrado,
        Tipo_Estudio_Pregrado,
        Semestre_Pregrado,
        Estado_Estudio_Pregrado,
        Estudio_Pregrado_Secundario,
        Tipo_Estudio_Pregrado_Secundario,
        Semestre_Pregrado_Secundario,
        Estado_Estudio_Pregrado_Secundario,
        Estudio_Pregrado_Terciario,
        Tipo_Estudio_Pregrado_Terciario,
        Semestre_Pregrado_Terciario,
        Estado_Estudio_Pregrado_Terciario,
        Estudio_Posgrado,
        Tipo_Estudio_Posgrado,
        Semestre_Posgrado,
        Estado_Estudio_Posgrado,
        Estudio_Posgrado_Secundario,
        Tipo_Estudio_Posgrado_Secundario,
        Semestre_Posgrado_Secundario,
        Estado_Estudio_Posgrado_Secundario,
        Estudio_Posgrado_Terciario,
        Tipo_Estudio_Posgrado_Terciario,
        Semestre_Posgrado_Terciario,
        Estado_Estudio_Posgrado_Terciario,
        Estudio_Complementario,
        Tipo_Estudio_Complementario,
        Semestre_Complementario,
        Estado_Estudio_Complementario,
        Estudio_Complementario_Secundario,
        Tipo_Estudio_Complementario_Secundario,
        Semestre_Complementario_Secundario,
        Estado_Estudio_Complementario_Secundario,
        Estudio_Complementario_Terciario,
        Tipo_Estudio_Complementario_Terciario,
        Semestre_Complementario_Terciario,
        Estado_Estudio_Complementario_Terciario,
        Idioma_Nativo,
        Idioma_Secundario,
        Nivel_Idioma_Secundario,
        Idioma_Terciario,
        Nivel_Idioma_Terciario,
        Fecha_Actualizacion FROM T_Socio WHERE Fecha_Corte BETWEEN ? AND ?`,

    // QUERY PARA TODO EL SOCIO COMPLETO
    getAllSocio:
        `SELECT 
        Documento,
        Nombres,
        Apellidos,
        Cargo,
        Cliente_Area,
        Programa_Area,
        Servicio,
        Sede,
        Etiquetas_Especiales_1,
        Etiquetas_Especiales_2,
        Etiquetas_Especiales_3,
        Fecha_Ingreso_Compania,
        Fecha_Ingreso_Formacion,
        Fecha_Ultima_Migracion,
        Formador,
        Grupo_Formacion,
        QM,
        Usuario_Red,
        Plataforma_1,
        Usuario_Plataforma_1,
        Plataforma_2,
        Usuario_Plataforma_2,
        Plataforma_3,
        Usuario_Plataforma_3,
        Plataforma_4,
        Usuario_Plataforma_4,
        Plataforma_5,
        Usuario_Plataforma_5,
        Fecha_Nacimiento,
        Pais_Nacimiento,
        Departamento_Nacimiento,
        Ciudad_Nacimiento,
        Edad,
        Genero,
        Tipo_Documento,
        Estado_Civil,
        Etnia,
        Grupo_Sanguineo,
        Factor_Sanguineo,
        Centro_Costos,
        Tipo_De_Centro_Costos,
        Estado_Empleado,
        Tipo_de_Baja,
        Fecha_Aplicacion_Retiro,
        Fecha_Actualizacion_Retiro,
        Comentario_Retiro,
        Causal_Terminacion,
        Director_Area,
        Gerente_Responsable,
        Jefe,
        Coordinador,
        Documento_Jefe_Inmediato,
        Jefe_Inmediato,
        Correo_Corporativo,
        Correo_Personal,
        Departamento_Residencia,
        Ciudad_Residencia,
        Zona_Residencia,
        Barrio_Residencia,
        Direccion_Residencia,
        Cubrimiento_Ruta,
        Telefono_Fijo_Principal,
        Telefono_Fijo_Secundario,
        Telefono_Celular_Principal,
        Telefono_Celular_Secundario,
        Contacto_Emergencia,
        Telefono_Contacto_Emergencia,
        Vehiculo_Propio,
        Tipo_Vehiculo,
        Computador_En_Casa,
        Internet_En_Casa,
        Velocidad_Internet,
        Sistema_Operativo_Computador,
        Memoria_RAM,
        Numero_Hijos,
        Numero_Personas_A_Cargo,
        Fondo_Pensiones,
        Fondo_Cesantias,
        Entidad_Salud,
        ARL,
        Caja_Compensacion_Familiar,
        Dias_Vacaciones,
        Periodos_Vacaciones,
        Estudio_Pregrado,
        Tipo_Estudio_Pregrado,
        Semestre_Pregrado,
        Estado_Estudio_Pregrado,
        Estudio_Pregrado_Secundario,
        Tipo_Estudio_Pregrado_Secundario,
        Semestre_Pregrado_Secundario,
        Estado_Estudio_Pregrado_Secundario,
        Estudio_Pregrado_Terciario,
        Tipo_Estudio_Pregrado_Terciario,
        Semestre_Pregrado_Terciario,
        Estado_Estudio_Pregrado_Terciario,
        Estudio_Posgrado,
        Tipo_Estudio_Posgrado,
        Semestre_Posgrado,
        Estado_Estudio_Posgrado,
        Estudio_Posgrado_Secundario,
        Tipo_Estudio_Posgrado_Secundario,
        Semestre_Posgrado_Secundario,
        Estado_Estudio_Posgrado_Secundario,
        Estudio_Posgrado_Terciario,
        Tipo_Estudio_Posgrado_Terciario,
        Semestre_Posgrado_Terciario,
        Estado_Estudio_Posgrado_Terciario,
        Estudio_Complementario,
        Tipo_Estudio_Complementario,
        Semestre_Complementario,
        Estado_Estudio_Complementario,
        Estudio_Complementario_Secundario,
        Tipo_Estudio_Complementario_Secundario,
        Semestre_Complementario_Secundario,
        Estado_Estudio_Complementario_Secundario,
        Estudio_Complementario_Terciario,
        Tipo_Estudio_Complementario_Terciario,
        Semestre_Complementario_Terciario,
        Estado_Estudio_Complementario_Terciario,
        Idioma_Nativo,
        Idioma_Secundario,
        Nivel_Idioma_Secundario,
        Idioma_Terciario,
        Nivel_Idioma_Terciario,
        Fecha_Actualizacion FROM T_Socio`,



    // QUERY PARA TODO EL LOS SENTIMIENTOS
    getFeelingData: `SELECT * FROM T_Feeling`,

    // QUERYS PARA TODO LOS TIPOS DE PERMISOS
    //QUERY LISTA DE USUARIOS PARA LOS PERMISOS
    permissionsUsers: `SELECT Documento, Nombres, Usuario_Red, Servicio, Cliente_Area FROM T_Socio WHERE Fecha_Corte = (SELECT MAX(Fecha_Corte) FROM T_Socio)`,

    //QUERY obtine la lista de los cargos para otorgrales los permisos 
    getListCargos: `SELECT * FROM T_Normal_Jobs ORDER BY Nombre_Cargo_Normalizado ASC`,

    //QUERY para saber a que modulos tiene permiso el usuario
    getPermissionsUsersCargo: `SELECT Cargo FROM T_Socio WHERE Usuario_Red = ?`,
    getPermissionsUsersCargoConcat: `SELECT DISTINCT jp.Id_Modulo, jp.Nombre_Cargo_Normalizado FROM T_Jobs_Permissions jp WHERE jp.Nombre_Cargo_Normalizado IN (SELECT jt.Cargo_Normalizado FROM T_Jobs_Traductor jt WHERE jt.Cargo_Oficial = ?)`,

    // QUERY para pasar el Nombre_Cargo_Normalizado para saber que permisos tiene el cargo 
    useCargoPermission: `SELECT DISTINCT jp.Id_Modulo, jp.Nombre_Cargo_Normalizado FROM T_Jobs_Permissions jp WHERE jp.Nombre_Cargo_Normalizado = ?`,

    //QUERY para otorgar permisos a los cargos
    getListNameCargo: `SELECT Id_Normalizado FROM T_Normal_Jobs WHERE Nombre_Cargo_Normalizado = ?`,
    insertModulesPermissions: `INSERT INTO T_Jobs_Permissions (Id_Normalizado, Nombre_Cargo_Normalizado, Id_Modulo) VALUES (?, ?, ?)`,
    deleteModulePermissions: `DELETE FROM T_Jobs_Permissions WHERE Id_Normalizado = ? AND Nombre_Cargo_Normalizado = ? AND Id_Modulo = ?`,

    //QUERYS PARA LOS CAMBIOS DE TURNOS
    //QUERY para seleccionar un turno es especifico
    selectShiftAdviser: `SELECT * FROM T_Shifts WHERE Documento = ? AND Fecha = ?`,

    //QUERYS DE IMPORTS
    //QUERY PARA INSERTAR LOS VALORES AUTOMATICAMNETE SIEMPRE Y CUANDO SE INSERTAR DATOS ENt_sHIFTS
    selectDataFromShifts: `SELECT Documento, Fecha, Turno_Ini, Turno_Fin FROM T_Shifts`,
    insertDataCollaborator_Dimensioning: `
    INSERT INTO T_Collaborator_Dimensioning (CodigoColaborador, Data, Inicio, CargaHoraria, DataAtualizado)
    VALUES ?
    ON DUPLICATE KEY UPDATE
    CodigoColaborador = VALUES(CodigoColaborador),
    Data = VALUES(Data),
    Inicio = VALUES(Inicio),
    CargaHoraria = VALUES(CargaHoraria),
    DataAtualizado = VALUES(DataAtualizado)
  `,

    //QUERY PARA TOMAR LOS VALORES INSERTADOS EN T_SHIFTS Y AUTOMATICAMENTE INSERTARLOS EN T_Collaborator_Novelty
    selectDataFromShiftsNovedad: `SELECT Documento, Fecha, Novedad FROM T_Shifts`,
    insertDataCollaborator_Novelty: `
    INSERT INTO T_Collaborator_Novelty (CodigoColaborador, Data, Novedad, DataAtualizado) 
    VALUES ?
    ON DUPLICATE KEY UPDATE
    CodigoColaborador = VALUES(CodigoColaborador),
    Data = VALUES(Data),
    Novedad = VALUES(Novedad),
    DataAtualizado = VALUES(DataAtualizado)
    `,

};

export default Queries;
